package com.yuan.leopardkit.db;

import com.yuan.leopardkit.db.dao.DaoSession;
import com.yuan.leopardkit.db.dao.FileModelDao;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "httpFile".
 */
public class FileModel {

    private Long key;
    private Integer type;
    private Integer state;
    private String url;
    private String fileName;
    private String fileSavePath;
    private Long progress;
    private Long fileLength;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient FileModelDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FileModel() {
    }

    public FileModel(Long key) {
        this.key = key;
    }

    public FileModel(Long key, Integer type, Integer state, String url, String fileName, String fileSavePath, Long progress, Long fileLength) {
        this.key = key;
        this.type = type;
        this.state = state;
        this.url = url;
        this.fileName = fileName;
        this.fileSavePath = fileSavePath;
        this.progress = progress;
        this.fileLength = fileLength;
    }

    public FileModel(Integer type, Integer state, String url, String fileName, String fileSavePath, Long progress, Long fileLength) {
        this.type = type;
        this.state = state;
        this.url = url;
        this.fileName = fileName;
        this.fileSavePath = fileSavePath;
        this.progress = progress;
        this.fileLength = fileLength;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getFileModelDao() : null;
    }

    public Long getKey() {
        return key;
    }

    public void setKey(Long key) {
        this.key = key;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileSavePath() {
        return fileSavePath;
    }

    public void setFileSavePath(String fileSavePath) {
        this.fileSavePath = fileSavePath;
    }

    public Long getProgress() {
        return progress;
    }

    public void setProgress(Long progress) {
        this.progress = progress;
    }

    public Long getFileLength() {
        return fileLength;
    }

    public void setFileLength(Long fileLength) {
        this.fileLength = fileLength;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
