package com.yuan.leopardkit.db.dao;

import android.database.sqlite.SQLiteDatabase;

import com.yuan.leopardkit.db.FileModel;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 *
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileModelDaoConfig;

    private final FileModelDao fileModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileModelDaoConfig = daoConfigMap.get(FileModelDao.class).clone();
        fileModelDaoConfig.initIdentityScope(type);

        fileModelDao = new FileModelDao(fileModelDaoConfig, this);

        registerDao(FileModel.class, fileModelDao);
    }
    
    public void clear() {
        fileModelDaoConfig.getIdentityScope().clear();
    }

    public FileModelDao getFileModelDao() {
        return fileModelDao;
    }

}
